on: push

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Get Arch
        run: |
          echo ::set-env name=ARCH::$(uname -m)
          echo ::set-env name=TIME::$(date "+%Y-%m-%d_%H:%M:%S")
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: env.TIME
          release_name: Release env.TIME
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
